# Generated by Django 4.2.2 on 2023-06-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_dadospaciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospaciente',
            old_name='percentual_gordura',
            new_name='gordura',
        ),
        migrations.RenameField(
            model_name='dadospaciente',
            old_name='percentual_musculo',
            new_name='musculo',
        ),
    ]
