# Generated by Django 4.2.2 on 2023-06-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0005_alter_opcao_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='imagem',
            field=models.FileField(blank=True, upload_to='opcao'),
        ),
    ]
